name: Test pins cache

on: push

jobs:
  test-pins-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::pins
      - name: Test pins Cache
        run: Rscript test-pins-cache-suggestion-1.R
      - name: Check what's in the cache
        run: |
          tree ~/.cache/pins/
      - name: Test pins Cache v2
        run: Rscript test-pins-cache-suggestion-2.R
      - name: Check what's in the cache
        run: |
          tree ~/.cache/pins/
